language: node_js
node_js:
    - "0.10"
sudo: true
dist: trusty

install:
    - npm install
script:
    - grunt
    
before_deploy:
    - sudo dpkg --add-architecture i386
    - sudo apt-get update
    - sudo apt-get install -y wine unrar
    - grunt setup
deploy:
    provider: releases
    api_key: ${GH_TOKEN}
    file: 
        - "dist/IBWUpdater-Client.zip"
        - "dist/IBWUpdater-Client.exec"
    skip_cleanup: true
    on:
        tags: true